#!/usr/bin/env python3
"""Generate the nested-ArUco landing pad models from world/pad_layout.py.

Run after changing anything in pad_layout, then respawn the world:

    python3 -m world.build_pads
    world/spawn_fleet.sh

WHY THIS IS GENERATED AND NOT HAND-MAINTAINED
---------------------------------------------
The pad geometry is load-bearing for the landing controller: config derives its
commit altitude and its no-climb altitude from world.pad_layout.coverage_m(), and
the controller assumes the pad it can see matches the pad it was told about. A
hand-edited PNG and a hand-edited constant drift apart silently, and the only
symptom is a landing that stops working at some altitude -- which is exactly the
failure this whole rewrite exists to remove.

Generating both the texture and the SDF from one source makes that drift
impossible, and scripts/preflight.py re-derives the coverage from the shipped
files so a stale texture fails on the bench rather than in the air.
"""

from __future__ import annotations

import argparse
import math
import sys
from pathlib import Path

import config
import world.marker_models as marker_models
import world.pad_layout as pad_layout

MODELS_DIR = Path(__file__).resolve().parent.parent / "sim" / "models"

MODEL_CONFIG = """<?xml version="1.0"?>
<model>
  <name>pad_{index}</name>
  <version>1.0</version>
  <sdf version="1.9">model.sdf</sdf>
  <description>
    Nested-ArUco landing pad {index} ({role}). Generated by world/build_pads.py --
    do not edit by hand. Markers: {markers}.
  </description>
</model>
"""

MODEL_SDF = """<?xml version="1.0" encoding="UTF-8"?>
<!--
  pad_{index} - {role}, {size} x {size} m, NESTED ArUco.

  GENERATED BY world/build_pads.py. Do not edit by hand; edit
  world/pad_layout.py and regenerate, or the texture and the controller's
  altitude budget will disagree.

  This pad carries FIVE markers at TWO scales, not one big marker:

{marker_table}

  The reason is the field of view. A single {legacy_marker:.3f} m marker -- what
  this pad used to carry -- overflows a 320x240 frame below 2.76 m, so ArUco
  could not read it over the last stretch of the descent. The landing loop
  answered the loss by climbing back to the search altitude, which restored the
  lock, so the drone descended, went blind, and climbed again: the hover the
  operator reported. At least one marker of this pad is readable from
  {cover_lo:.2f} m to {cover_hi:.2f} m.
-->
<sdf version='1.9'>
  <model name='pad_{index}'>
    <static>true</static>
    <pose>0 0 0.001 0 0 0</pose>
    <link name='base'>
      <visual name='base_visual'>
        <geometry>
          <plane>
            <normal>0 0 1</normal>
            <size>{size} {size}</size>
          </plane>
        </geometry>
        <material>
          <diffuse>1 1 1 1</diffuse>
          <specular>0.1 0.1 0.1 1</specular>
          <pbr>
            <metal>
              <albedo_map>model://pad_{index}/{texture}</albedo_map>
              <metalness>0.0</metalness>
              <roughness>1.0</roughness>
            </metal>
          </pbr>
        </material>
      </visual>
    </link>
  </model>
</sdf>
"""


def _marker_table(index: int, fx_px: float, tan_h: float, tan_v: float) -> str:
    rows = []
    for marker in pad_layout.pad_markers(index):
        low, high = marker.altitude_band_m(fx_px, tan_h, tan_v)
        rows.append(
            f"    id {marker.marker_id:>3}  {marker.side_m:.2f} m at "
            f"({marker.x_m:+.2f}, {marker.y_m:+.2f}) m  "
            f"readable {low:.2f}-{high:.2f} m"
        )
    return "\n".join(rows)


def build(index: int, models_dir: Path, fx_px: float, tan_h: float, tan_v: float) -> list[Path]:
    """Write pad_<index>'s texture, model.sdf and model.config. Returns the paths."""
    import cv2

    role = marker_models.ID_TO_ROLE.get(index, f"pad {index}")
    directory = models_dir / f"pad_{index}"
    directory.mkdir(parents=True, exist_ok=True)

    texture_name = f"pad_{index}.png"
    texture = pad_layout.render_pad_texture(index)
    cv2.imwrite(str(directory / texture_name), texture)

    cover_lo, cover_hi = pad_layout.coverage_m(fx_px, tan_h, tan_v, index)
    markers = pad_layout.pad_markers(index)

    (directory / "model.sdf").write_text(
        MODEL_SDF.format(
            index=index,
            role=role,
            size=f"{pad_layout.PAD_SIZE_M:.1f}",
            texture=texture_name,
            marker_table=_marker_table(index, fx_px, tan_h, tan_v),
            legacy_marker=pad_layout.PAD_SIZE_M * 0.796,
            cover_lo=cover_lo,
            cover_hi=cover_hi,
        )
    )
    (directory / "model.config").write_text(
        MODEL_CONFIG.format(
            index=index,
            role=role,
            markers=", ".join(str(m.marker_id) for m in markers),
        )
    )

    # The old single-marker texture must go. Leaving it in place is an invitation
    # for a stale <albedo_map> reference to keep the undecodable pad alive.
    legacy = directory / f"aruco_{index}.png"
    removed = []
    if legacy.exists():
        legacy.unlink()
        removed.append(legacy)

    return [directory / texture_name, directory / "model.sdf", directory / "model.config", *removed]


def verify(index: int) -> tuple[bool, str]:
    """Detect the generated texture and confirm every expected marker decodes.

    Generating a texture that does not decode is the single most damaging thing
    this script could do quietly -- it is finding F1 all over again -- so the
    texture is read back through the real detector before we call it done.
    """
    import cv2

    directory = MODELS_DIR / f"pad_{index}"
    image = cv2.imread(str(directory / f"pad_{index}.png"), cv2.IMREAD_GRAYSCALE)
    if image is None:
        return False, "texture missing"

    detector = cv2.aruco.ArucoDetector(
        cv2.aruco.getPredefinedDictionary(getattr(cv2.aruco, pad_layout.ARUCO_DICTIONARY)),
        cv2.aruco.DetectorParameters(),
    )
    _, ids, _ = detector.detectMarkers(image)
    found = set(ids.flatten().tolist()) if ids is not None else set()
    expected = {m.marker_id for m in pad_layout.pad_markers(index)}

    if found >= expected:
        return True, f"decodes {sorted(expected)}"
    return False, f"expected {sorted(expected)}, texture decodes only {sorted(found)}"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--models-dir", type=Path, default=MODELS_DIR, help="where sim/models lives"
    )
    args = parser.parse_args(argv)

    fx_px = config.CAMERA_FX_PX
    tan_h = math.tan(config.CAMERA_HFOV_RAD / 2.0)
    tan_v = (config.CAMERA_HEIGHT_PX / 2.0) / fx_px

    print(pad_layout.describe(fx_px, tan_h, tan_v))
    print()

    ok = True
    for index in range(pad_layout.PAD_COUNT):
        written = build(index, args.models_dir, fx_px, tan_h, tan_v)
        passed, detail = verify(index)
        ok &= passed
        flag = "OK  " if passed else "FAIL"
        print(f"{flag} pad_{index}: {detail}")
        for path in written:
            print(f"       {path.relative_to(args.models_dir.parent.parent)}")

    if not ok:
        print("\nA generated texture does not decode. Do not fly this.", file=sys.stderr)
        return 1

    print(
        "\nRegenerate the world so Gazebo picks these up:\n"
        "    source sim/env.sh && world/spawn_fleet.sh\n"
        "then confirm with:\n"
        "    python3 scripts/preflight.py"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
