"""Landing-pad model mapping: pad role <-> Gazebo model <-> ArUco marker ID.

WHY EACH PAD GETS ITS OWN MARKERS
---------------------------------
The documented behaviour is precision landing on ArUco IDs 0, 1 and 2 with
disambiguation. Before remediation, drone_logic.py spawned `model://arucotag`
for all three pads and then asked the detector for marker 0 on every leg, so
three identical tags stood within metres of each other and the drone had no way
to tell the pickup pad from the drop pad from home. Distinct IDs are what make
that filter mean anything.

WHY NOT `model://arucotag` (finding F1)
--------------------------------------
That model's 354x354 texture fills its plane edge to edge with no white quiet
zone. ArUco's contour stage cannot segment a marker without one: the texture
decodes in ZERO of OpenCV's 27 predefined dictionaries as rendered. So the pad
could never be locked on to at all.

WHY NOT ONE BIG MARKER EITHER
-----------------------------
Fixing F1 with a single large decodable marker fixed the wrong half of the
problem. A marker large enough to read from 6 m is too large to FIT the 320x240
frame below about 2.5 m, so the drone went blind partway down every descent,
and the landing loop answered that by climbing back to the search altitude --
the hover the operator reported.

The shipped pads are generated by world/build_pads.py from world/pad_layout.py
and carry FIVE markers at TWO scales each: a small centre marker for the last
few metres and four larger ones in a cross for the approach. At least one is
readable from 0.5 m to beyond 8 m. scripts/preflight.py asserts that every
declared marker really decodes, so a regression here fails on the bench instead
of in the air.

IDS
---
The CENTRE marker of pad p keeps id p, so ROLE_TO_ID and every caller that says
"land on marker 1" are unchanged. Pad p's outer ring takes ids 10p+10..10p+13.
world.pad_layout owns that scheme; this module owns the role mapping.
"""

PAD_MODELS = {
    "pickup_pad": "model://pad_0",
    "drop_pad": "model://pad_1",
    "home_pad": "model://pad_2",
}
"""Pad role -> Gazebo model URI. Resolved via GZ_SIM_RESOURCE_PATH; source
sim/env.sh so DroneProgram's sim/models is on that path."""

ROLE_TO_ID = {
    "pickup_pad": 0,
    "drop_pad": 1,
    "home_pad": 2,
}
"""Pad role -> the DICT_4X4_50 marker ID printed on it."""

ID_TO_ROLE = {marker_id: role for role, marker_id in ROLE_TO_ID.items()}

ARUCO_DICTIONARY = "DICT_4X4_50"
"""The one dictionary the whole system uses; world.pad_layout is the source of
truth and this re-exports it for callers that already import from here.

Do not widen it. 4x4 carries the fewest bits and so survives the smallest
apparent size, which is what matters on a 320x240 frame -- and the pad textures
also decode under other dictionaries, so a multi-dictionary detector would
report phantom markers that no leg is looking for."""

LEG_ORDER = ("pickup_pad", "drop_pad", "home_pad")
"""Canonical 3-leg delivery sequence. drone_logic builds its legs from this
rather than from three hardcoded zeroes."""


def marker_id_for_role(role: str) -> int:
    """ArUco ID for a pad role.

    Raises:
        KeyError: on an unknown role, rather than silently defaulting to 0 --
            which is how all three legs ended up hunting for marker 0.
    """
    return ROLE_TO_ID[role]


def model_uri_for_role(role: str) -> str:
    """Gazebo model URI for a pad role."""
    return PAD_MODELS[role]
